### ISSUE TITLE
segfault when screen not plugged in

### ISSUE THREAD

**Issue by dgossow** [ros-visualization/oculus_rviz_plugins#11]
I get this when the usb but not the dvi cable is plugged in:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffad2a0e0c in rviz_oculus::OculusDisplay::onFullScreenChanged (this=0xfe0ef0) at /wg/stor5/dgossow/wsoculus/src/rviz_oculus/src/oculus_display.cpp:200
200       oculus_->getHMDDevice()->GetDeviceInfo( &info );
(gdb) bt
#0  0x00007fffad2a0e0c in rviz_oculus::OculusDisplay::onFullScreenChanged (this=0xfe0ef0) at /wg/stor5/dgossow/wsoculus/src/rviz_oculus/src/oculus_display.cpp:200
#1  0x00007fffad2a06a6 in rviz_oculus::OculusDisplay::onInitialize (this=0xfe0ef0) at /wg/stor5/dgossow/wsoculus/src/rviz_oculus/src/oculus_display.cpp:139
#2  0x00007ffff7aa234a in rviz::Display::initialize (this=0xfe0ef0, context=<optimized out>) at /u/dgossow/wsrviz/src/rviz/src/rviz/display.cpp:94
#3  0x00007ffff7ab3107 in rviz::DisplayGroup::load (this=0xaad720, config=...) at /u/dgossow/wsrviz/src/rviz/src/rviz/display_group.cpp:106
#4  0x00007ffff7b581ee in rviz::VisualizationManager::load (this=0x945cf0, config=...) at /u/dgossow/wsrviz/src/rviz/src/rviz/visualization_manager.cpp:446
#5  0x00007ffff7b52341 in rviz::VisualizationFrame::load (this=0x84a7e0, config=...) at /u/dgossow/wsrviz/src/rviz/src/rviz/visualization_frame.cpp:729
#6  0x00007ffff7b53c0a in rviz::VisualizationFrame::loadDisplayConfig (this=0x84a7e0, qpath=...) at /u/dgossow/wsrviz/src/rviz/src/rviz/visualization_frame.cpp:650
#7  0x00007ffff7b55445 in rviz::VisualizationFrame::initialize (this=0x84a7e0, display_config_file=...) at /u/dgossow/wsrviz/src/rviz/src/rviz/visualization_frame.cpp:317
#8  0x00007ffff7b5db62 in rviz::VisualizerApp::init (this=0x7fffffffdfe0, argc=1, argv=<optimized out>) at /u/dgossow/wsrviz/src/rviz/src/rviz/visualizer_app.cpp:239
#9  0x0000000000400abe in main (argc=1, argv=0x7fffffffe118) at /u/dgossow/wsrviz/src/rviz/src/rviz/main.cpp:39

```

**Comment by dgossow** [comment]
fixed in 4f226b6acf92944bdfb6bcc0279bb0f80c8a4f80
